openapi: 2.0.3
info:
  title: Assignment-phase-01 - OpenAPI 3.0
  description: |-
    This is the API for Nine25 Assignment Phase 1
  contact:
    email: jamesbirrellgray@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://TBC/
tags:
  - name: People API
    description: Search for the people
paths:
  # [GET] People
  /people:
      get:
        tags:
          - People
        summary: Find the people
        description: Multiple status values can be provided with comma separated strings
        operationId: findThePeople
        parameters:
          - name: page
            in: query
            description: Page number for pagination
            required: false
            schema:
              type: number
          - name: per_page
            in: query
            description: Define number of items per page
            required: false
            schema:
              type: number
          - name: sort_by
            in: query
            description: Sort the results
            required: false
            type: "string"
            explode: true
            enum: 
              - "Alphabetical"
              - "Appearances"
            items:
              type: "string"
              default: "Alphabetical"
          - name: order
            in: query
            description: Order the results
            required: false
            type: "string"
            explode: true
            enum:
              - "Accending"
              - "Deccending"
            items:
              type: "string"
              default: "Accending"
        responses:
          '200':
            description: successful operation
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/definitions/Person'          
              application/xml:
                schema:
                  type: array
                  items:
                    $ref: '#/definitions/Person'
          '400':
            description: Invalid status value
# definitions

definitions:
  Person:
    type: object
    properties:
      name:
        type: string
        example: Jimmy
      height:
        type: string
        example: '172'
      url:
        type: string
        example: http://thisapi.com/person/1
    xml:
      name: person
  ApiResponse:
    type: object
    properties:
      code:
        type: integer
        format: int32
      type:
        type: string
      message:
        type: string
    xml:
      name: '##default'
schemes:
  - https
  - http
